version: "3.9"

services:
  tofu:
    build: .
    container_name: opentofu
    working_dir: /workspace

    volumes:
      - ./:/workspace
      - ~/.oci:/root/.oci
      - ~/.ssh:/root/.ssh

    environment:
      - TF_LOG=INFO

    stdin_open: true
    tty: true