services:
  tofu:
    build: .
    container_name: opentofu
    working_dir: /workspace

    volumes:
      - ./GCP:/workspace
      - ./.env:/root/.config/gcloud   # ✅ use your local config folder
      - ~/.ssh:/root/.ssh

    environment:
      - TF_LOG=INFO
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/opentofu-cred.json

    stdin_open: true
    tty: true